/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.*;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class user_home extends javax.swing.JFrame {

    /**
     * Creates new form user_home_1
     */
    public user_home(String email) {
        initComponents();
        setSize(500,500);
        lb.setText("Welcome: "+email);
        loadcategory();
        mainpanel.setOpaque(true);
        mainpanel.setBackground(Color.red);
    }
     void loadcategory()
    {
        String ans=myClient_3.fetchcat();
        System.out.println(ans);
        StringTokenizer st=new StringTokenizer(ans,";;");
        int n=st.countTokens();
        JButton arr[]=new JButton[n];
        int x=10,y=100;
        for(int i=0 ;i<n ;i++)
        {
            String row=st.nextToken();
            StringTokenizer st1=new StringTokenizer(row,"$");
             String name=st1.nextToken();
             String photo=st1.nextToken();
            // System.out.println(photo);
             
             arr[i]=new JButton(name);
             
             ImageIcon ic= new ImageIcon(photo);
             Image img  =ic.getImage().getScaledInstance(40,40,Image.SCALE_SMOOTH);
            arr[i].setIcon(new ImageIcon(img));
            
            
            
             arr[i].setBounds(x, y,120, 40);
            // add(arr[i]);
            
            arr[i].addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    //JOptionPane.showMessageDialog(rootPane, name+" clicked ");
                    fetch_movies obj=new fetch_movies(name);
                    obj.setVisible(true);
                    
                }
            });
            mainpanel.add(arr[i]);
             mainpanel.repaint(); // refresh the data
             
             if(x<=210)
             {
                  x=x+120;
             }
             else
             {
                 x=10;
                 y=y+50;
             }
            
        }
        mainpanel.setPreferredSize(new Dimension(400,n*50));
        
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lb.setForeground(new java.awt.Color(204, 0, 204));
        lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb.setText("WELCOME");
        getContentPane().add(lb);
        lb.setBounds(0, 0, 500, 50);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 500, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home(" ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
